baseurl = "/"
languageCode = "en-us"
title = "Amy's website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Projects"
    url = "/projects/"
  
    
[[menu.main]]
    name = "CV"
    url = "/CV/"
    
[[menu.main]]
    name = "Outreach"
    url = "/outreach/"
    
    
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/aef1004"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

