baseurl = "https://amy-fox.netlify.com/"
languageCode = "en-us"
title = "Amy's website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Projects"
    url = "/projects/"
  
    
[[menu.main]]
    name = "CV"
    url = "/CV/"
    
[[menu.main]]
    name = "Outreach"
    url = "/outreach/"
    
    
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/aef1004"


[params]
    mainSections = ["About"]
    
    description = "A website built through Hugo and blogdown."

  
    # path to the favicon, under "static"
    favicon = "logo2.png"


    [params.logo]
    url = "logo2.png"
    width = 50
    height = 50
    alt = "Logo"